### ISSUE TITLE
Criar base do site em Jekyll

### ISSUE THREAD

**Issue by Dkmister** [webiwg/historia-web-pt#1]

**Comment by fititnt** [comment]
Base do site foi criada. A URL atual está em https://dkmister.github.io/historia-web-pt/.

Creio que para rodar em localhost, é executar

```
bundle install
bundle exec jekyll serve
```

E acessar em http://127.0.0.1:4000/historia-web-pt/

**Comment by fititnt** [comment]
O mínimo dos mínimos que poderiam ser feitos já estão inclusos. Agora tem que ir um pouco além não customização desse template.

Creio que vou abrir outros issues já pra ficar de referência para quem vai aplicar isso nos outros repositórios, e ficar bem didático.

**Comment by rcgivisiez** [comment]
@Dkmister como está isso aqui? alguém está cuidando?
