### ISSUE TITLE
URL para o repositório provisória e permanente

### ISSUE THREAD

**Issue by rcgivisiez** [webiwg/historia-web-pt#13]
Tanto para o projeto de textos de acessibilidade quanto para o de história, é pertinente ter nesse momento 1) URL provisória e 2) URL permanente.

Em ambos os casos, é importante deixar a URL no topo da tela do Github.

Depende em parte do issue #1.

**Comment by fititnt** [comment]
A URL usada neste momento é http://historia.pt.webiwg.org/. É bem provável que ela acabe sendo a URL permanente.

o fato de ter "pt." na URL é para permitir que mais tarde também tenhamos outros idiomas, em especial o espanhol.
